### PR TITLE
Bug-Fix and Enhacement version v0.1.1

### PR DESCRIPTION
**Pull request by Nicolas-Klatzer**
# Summary
New Version release for openhiven.py with bug-fixes and enhancements for the WebSocket as well as the HTTP CLient

## Changes
- Rewrite websocket
- Integration of .env
- Enhancements in the Connection class and ws

### CODE REVIEW

**Review by Nxybi — CHANGES_REQUESTED** [review]
I don't see the point of most of these changes? Care to explain them in comments?

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> I don't see the point of most of these changes? Care to explain them in comments?

Well, the thing I noticed was that we have 3 different libraries for HTTP and WebSockets. So I wanted to rewrite the websocket only to use one library that can then enhance performance since we don't need to create multiple sessions for multiple instances of HTTP connections. The changes are rather limited though and mostly just for performance improvements and bug fixes, so it's only a "small" change, but that should definitely improve a lot

**Comment by Nxybi** [comment]
> > I don't see the point of most of these changes? Care to explain them in comments?
> 
> Well, the thing I noticed was that we have 3 different libraries for HTTP and WebSockets. So I wanted to rewrite the websocket only to use one library that can then enhance performance since we don't need to create multiple sessions for multiple instances of HTTP connections. The changes are rather limited though and mostly just for performance improvements and bug fixes, so it's only a "small" change, but that should definitely improve a lot

~~write your own~~
I see

**Review by Nxybi — APPROVED** [review]
All good!

**Comment by Nxybi** [comment]
7 days past due date - @FrostbyteSpace/openhiven need a bigger time window?

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> 7 days past due date - @FrostbyteSpace/openhiven need a bigger time window?

Tbh I just need to finally take the time and overall finish everything

**Comment by Nicolas-Klatzer** [comment]
Okay, should finish that tomorrow and hopefully fix it so everything is ready for the docs and preparations for v0.2

**Comment by Nicolas-Klatzer** [comment]
Finished v0.1.1 and last bugs and traceback changes. Will merge and make room for v0.1.2 or possibly v0.2

**Pull request merged**
