### PR TITLE
Merge of main and v0.1 dev 

### PR DESCRIPTION
**Pull request by Nicolas-Klatzer**
# Summary
First stable pre-release v0.1. Will implement basic functionality and usage of the Hiven API, swarm and overall Environment.

### CODE REVIEW

**Review by Nxybi — APPROVED** [review]
MILESTONE IS F E C K I N DONE KUDO WHY HAVENT WE MERGED N RELEASE YET?!

**Comment by Nxybi** [comment]
I know I have no sanity, but I am so not fucking clicking "Viewed Changes" 513 times

**Comment by Nicolas-Klatzer** [comment]
@Nxybi pokes Robyn time to review UwU

**Comment by Nxybi** [comment]
> @Nxybi pokes Robyn time to review UwU

You're lucky Zincy is AFK. Gimme an hour and a ☕

**Review by Nxybi — APPROVED** [review]
I am not clicking 513 as viewed. Approved - ready for release!

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> > @Nxybi pokes Robyn time to review UwU
> 
> You're lucky Zincy is AFK. Gimme an hour and a ☕

Okay already making water hot

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> I am not clicking 513 as viewed. Approved - ready for release!

you sure love your job don't ya?

**Comment by Nxybi** [comment]
> > I am not clicking 513 as viewed. Approved - ready for release!
> 
> you sure love your job don't ya?

Not when you change 513 files and add 200k lines, jfc.

**Pull request merged**
