### PR TITLE
Merge for version update v0.1.1.3

### PR DESCRIPTION
**Pull request by Nicolas-Klatzer**
# Summary
Merge for new bug-fixes, functionality updates and changes in documentation

## Changes
- Fixed UserClient bug of a passed user as a parameter not being recognised and silence-failing
- Fixed property bug and raised exceptions when calling property values
- Removed nest_asyncio and fixed run() and double event_loop creation
- Rewrite of HTTP requests for better logging and details about errors
- Added new /doc-examples for openhiven.py usage examples
- Fixed `utils.dispatch_func_if_exists()` crash bug causing the websocket to crash
- Fixed `.env` not found error causing the startup to fail
- Fixed ExecutionLoop Bug causing an object to be used as a list and therefore failing to correctly append objects to it
- Added Option to add an event_loop to `openhivenpy.HivenClient.run()`
- Rewrote restart and added restart option to `openhivenpy.HivenClient.run(restart: bool)`
- Changed Restart Handling to only restart if the startup was successful one time

### CODE REVIEW

**Comment by Nxybi** [comment]
id like to ask github on why tf both:
A) README conflicted
B) WHY WE GOT A NOTI FOR THIS SEVERAL DAYS LATER

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> id like to ask github on why tf both:
> A) README conflicted
> B) WHY WE GOT A NOTI FOR THIS SEVERAL DAYS LATER

A) I think your commit caused it
B) I opened this rn

**Comment by Nxybi** [comment]
> > id like to ask github on why tf both:
> > A) README conflicted
> > B) WHY WE GOT A NOTI FOR THIS SEVERAL DAYS LATER
> 
> A) I think your commit caused it
> B) I opened this rn

A) ok prob
B) "Nicolas-Klatzer added 6 commits 8 days ago"

**Comment by Nicolas-Klatzer** [comment]
Will merge when #37 is finished

**Comment by Nicolas-Klatzer** [comment]
Will merge for release v0.1.1.3 for bug-fixes in the utils extension and a major .env bug. => v0.1.2 will be merged in new pr

**Pull request merged**
